modules/service/controllers/DefaultController.php
<?php

namespace app\modules\service\controllers;

use yii\web\Controller;

/**
 * Default controller for the `service` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}

modules/service/controllers/HospitalsController.php
<?php

namespace app\modules\service\controllers;

use app\models\Medcenter;
use app\models\Profession;
use yii\web\Controller;

/**
 * Hospital controller for the `service` module
 */
class HospitalsController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */

    public function actionIndex()
    {
        $medcenter = Medcenter::find()->all();
        return $this->render('index', [
            'medcenter' => $medcenter,
        ]);
    }

    public function actionView($id=null)
    {
        $medcenter = Medcenter::findOne([$id]);
        return $this->render('view', [
            'medcenter' => $medcenter,
        ]);
    }

    public function actionDoctors($id=null)
    {
        $medcenter = Medcenter::findOne([$id]);
        return $this->render('doctors', [
            'medcenter' => $medcenter,
        ]);
    }

    public function actionRegions()
    {
        return $this->render('regions');
    }
}

modules/service/controllers/RecordController.php
<?php

namespace app\modules\service\controllers;

use app\models\Doctor;
use app\models\Medcenter;
use app\models\Profession;
use app\models\WrittenToDoctor;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

/**
 * Record controller for the `service` module
 */
class RecordController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
//                'only' => ['timetable'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionProfiles($id=null)
    {
        if($id){
            $doctors = Profession::findOne($id)->getDoctors()->orderBy('work')->all();
            return $this->render('record_table', [
                'doctors' => $doctors,
            ]);
        }
        $professions = Profession::find()->orderBy('prof_name')->all();
        return $this->render('profiles', [
            'professions' => $professions,
        ]);
    }

    public function actionDoctors($id=null)
    {
        if($id){
            $doctors = Profession::findOne($id)->getDoctors()->orderBy('work')->all();
            $professionName = Profession::findOne($id)->prof_name;
            return $this->render('record_table', [
                'doctors' => $doctors,
                'professionName' => $professionName,
            ]);
        }
        return $this->redirect([404]);
    }

    public function actionHospitals($id)
    {
        $medcenter = Medcenter::findOne([$id]);
        return $this->render('hospitals');
    }

    public function actionRegions()
    {
        return $this->render('regions');
    }

    /**
     * @param int $id
     * @param int $time
     * @return void|\yii\web\Response
     */
    public function actionAdd($id=1, $time=null)
    {
        $doctor = Doctor::findOne($id);
        $wtd = new WrittenToDoctor();
        $wtd->doctor = $doctor->id;
        $wtd->user = \Yii::$app->user->identity->getId();
        $wtd->date = $time."";
        if($wtd->save()){
            return $this->goBack();
        }
        else{
            var_dump($wtd);return;
            return $this->goHome();
        }
    }

    public function actionSearch(){
        $search = \Yii::$app->request->post('search');
        $doctor = Doctor::find()->where(['like', 'full_name', $search])->all();
        return $this->render('search', [
            'result' => $doctor,
        ]);

    }
}

modules/service/controllers/ScheduleController.php
<?php

namespace app\modules\service\controllers;

use app\models\Doctor;
use app\models\WrittenToDoctor;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\web\Controller;

/**
 * Default controller for the `service` module
 */
class ScheduleController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
//                'only' => ['timetable'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public $defaultAction = 'info';
    public function actionInfo($id)
    {
        $doctor = Doctor::findOne($id);
        return $this->render('info', [
            'doctor' => $doctor,
        ]);
    }
    public function actionTimetable($id)
    {
        $doctor = Doctor::findOne($id);
        $writtens = WrittenToDoctor::find()->where(['doctor'=>$doctor->id])->all();
        return $this->render('timetable', [
            'doctor' => $doctor,
            'writtens' => $writtens,
        ]);
    }
}

modules/service/views/default/index.php
<div class="service-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

modules/service/views/hospitals/doctors.php
<?php
/* @var $this yii\web\View */
?>
<div class="wrapper">
    <input value="13003269" id="Lpu_id" type="hidden">
    <h1>
        <?=$medcenter->name?>
        <span class="pseudoTab">
            <span class="org_light">
                <a href="<?=\Yii::$app->urlManager->createUrl(['service/hospitals/view', 'id'=>$medcenter->id])?>">Umumiy ma'lumot</a>
            </span>
            <span class="selected spec_dark">
                <a href="<?=\Yii::$app->urlManager->createUrl(['service/hospitals/doctors', 'id'=>$medcenter->id])?>">Mutahasislar</a>
            </span>
        </span>
    </h1>
    <table width="100%">
        <tbody><tr>
            <th scope="col" style="width: 300px;">Mutahasislik</th>
            <th scope="col">Doktor</th>
            <th scope="col">Status</th>
        </tr>
        <?php foreach ($medcenter->getDoctors()->all() as $doctor) {?>
            <tr>
                <td><?=$doctor->getProfession()->one()->prof_name?></td>
                <td><a href="<?=\Yii::$app->urlManager->createUrl(['service/schedule/info', 'id'=>$doctor->id])?>"><?=$doctor->full_name?></a></td>
                <td><span class="Schedule not_free"></span></td>
            </tr>
        <?php }?>
        </tbody>
    </table>

    <div class="mapContainer">
        <div id="map"></div>
    </div>
</div>

modules/service/views/hospitals/index.php
<?php
/* @var $this yii\web\View */
?>

<div class="wrapper">
    <h1>Tibbiy muassasalar</h1>
    <div class="medOrganizationsTable">
        <div class="moTableDetail">
            <?php foreach ($medcenter as $mc): ?>
            <a class="moDetail" href="<?=\Yii::$app->urlManager->createUrl(['service/hospitals/view', 'id'=>$mc->id])?>" style="display: block;">
                <div class="leftAlignmentTableCell"></div>
                <div class="leftMoContent">
                    <span class="lpu-name"><?=$mc->name?></span><br>
                    <span class="lpu-address"><?=$mc->address?></span>
                </div>
                <div class="mark-stars "></div>
            </a>
            <?php endforeach; ?>
        </div>

    </div>
</div>

modules/service/views/record/profiles.php
<?php
/* @var $this yii\web\View */
?>
<div class="wrapper">
    <div class="docRecordingBlock">
        <h1><a href="/user/cards"><?=\Yii::$app->user->identity->name?> <?=\Yii::$app->user->identity->family?></a> <span>записывается к врачу</span></h1>
        <div class="clientLpuAttachmentsTab"><span>Прикрепление</span></div>
        <div class="clientLpuAttachments">
            <p><span>
				Основное прикрепление:
				</span>
                <a href="/service/hospitals/view/13003269">ГБУЗ АО "ГП №2", г Астрахань, ул Соликамская, д 8</a>
                / <a href="/service/hospitals/regions/13003269#174">участок 1</a>											 / <a href="/service/record/908205/36852/timetable">Бодрова Разия Фазлыевна</a>
            </p>
            <p><a class="isAttachmentWrong" href="#">Сообщить о неверном прикреплении</a></p>
        </div>
        <div class="clearFix"></div>
    </div>        <ul class="steps step1">
        <li><a href="/service/record/908205/profiles">Выберите специальность</a></li>
        <li><span>Специалист</span></li>
        <li><span>Дата и время</span></li>
    </ul>


    <h1>Поиск врача</h1>
    <form class="doc_search" action="<?=\Yii::$app->urlManager->createUrl(['service/record/search'])?>" method="post">
        <p class="inputFieldwithCase">
            <input name="<?=\Yii::$app->request->csrfParam?>" value="<?=\Yii::$app->request->csrfToken?>" type="hidden">
            <input name="search" autocomplete="off" class="autoCompleteInput ui-autocomplete-input" placeholder="Введите ФИО или специальность врача" type="text">
            <a class="button search"></a>
        </p>
    </form>

    <dl class="selectDoc filtered">
        <dt class="allDoctors selected" style="display: none;"></dt>
        <dd>
            <ul>
                <li>
                    <ul>
                        <span class="big">А</span>
                        <?php foreach ($professions as $profession){ ?>
                            <li><?=\yii\bootstrap\Html::a($profession->prof_name, ['record/doctors', 'id'=>$profession->id, 'step'=>2])?></li>
                        <? } ?>
                        <li><a href="/service/record/908205/402182/0/doctors">Акушер - гинеколог</a></li>
                        <li><a href="/service/record/908205/35124/0/doctors">Аллерголог-иммунолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">В</span>
                        <li><a href="/service/record/908205/0/203/doctors">Врач общей практики-семейный врач</a></li>
                        <li><a href="/service/record/908205/35231/0/doctors">Врач функциональной диагностики</a></li>
                    </ul></li>
                <li>
                    <ul>
                        <span class="big">Г</span>
                        <li><a href="/service/record/908205/35131/0/doctors">Гастроэнтеролог</a></li>
                        <li><a href="/service/record/908205/35132/0/doctors">Гематолог</a></li>
                    </ul
                </li>
                <li>
                    <ul>
                        <span class="big">Д</span>
                        <li>
                            <a href="/service/record/908205/35136/0/doctors">Дерматовенеролог</a>
                        </li>
                        <li>
                            <a href="/service/record/908205/35206/0/doctors">Детский стоматолог</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">И</span>
                        <li>
                            <a href="/service/record/908205/35148/0/doctors">Инфекционист</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">К</span>
                        <li>
                            <a href="/service/record/908205/35149/0/doctors">Кардиолог</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Л</span>
                        <li><a href="/service/record/908205/35154/0/doctors">Лабораторной диагностики</a></li>
                        <li><a href="/service/record/908205/35161/0/doctors">Лечебная физкультура</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Н</span>
                        <li><a href="/service/record/908205/35173/0/doctors">Невролог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">О</span>
                        <li><a href="/service/record/908205/35180/0/doctors">Онколог</a></li>
                        <li><a href="/service/record/908205/35184/0/doctors">Оториноларинголог</a></li>
                        <li><a href="/service/record/908205/35185/0/doctors">Офтальмолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">П</span>
                        <li><a href="/service/record/908205/35188/0/doctors">Педиатр</a></li>
                        <li><a href="/service/record/908205/35195/0/doctors">Пульмонолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Р</span>
                        <li><a href="/service/record/908205/35197/0/doctors">Ревматолог</a></li>
                        <li><a href="/service/record/908205/35198/0/doctors">Рентгенолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">С</span>
                        <li><a href="/service/record/908205/35205/0/doctors">Стоматолог</a></li>
                        <li><a href="/service/record/908205/35210/0/doctors">Стоматолог хирург</a></li>
                        <li><a href="/service/record/908205/35208/0/doctors">Стоматолог-ортопед</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Т</span>
                        <li><a href="/service/record/908205/35217/0/doctors">Терапевт и врач общ. практики</a></li>
                        <li><a href="/service/record/908205/35220/0/doctors">Травматолог-ортопед</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">У</span>
                        <li><a href="/service/record/908205/35226/0/doctors">Ультразвуковой диагностики</a></li>
                        <li><a href="/service/record/908205/35228/0/doctors">Уролог</a></li>
                        <li><a href="/service/record/908205/35139/0/doctors">Уролог детский</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Ф</span>
                        <li><a href="/service/record/908205/35229/0/doctors">Физиотерапевт</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Х</span>
                        <li><a href="/service/record/908205/35232/0/doctors">Хирург</a></li>
                        <li><a href="/service/record/908205/35140/0/doctors">Хирург детский</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Ц</span>
                        <li><a href="/service/record/908205/35255/0/doctors">Центр здоровья</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Э</span>
                        <li><a href="/service/record/908205/35242/0/doctors">Эндокринолог</a></li>
                        <li><a href="/service/record/908205/35141/0/doctors">Эндокринолог детский</a></li>
                        <li><a href="/service/record/908205/35243/0/doctors">Эндоскопист</a></li>
                    </ul>
                </li>
            </ul>
        </dd>
    </dl>
</div>

modules/service/views/record/record.php
<?php
/* @var $this yii\web\View */
?>
<div class="wrapper">
    <div class="docRecordingBlock">
        <h1><a href="/user/cards"><?=\Yii::$app->user->identity->name?></a> <span>записывается к врачу</span></h1>
        <div class="clientLpuAttachmentsTab"><span>Прикрепление</span></div>
        <div class="clientLpuAttachments">
            <p><span>
				Основное прикрепление:
				</span>
                <a href="/service/hospitals/view/13003269">ГБУЗ АО "ГП №2", г Астрахань, ул Соликамская, д 8</a>
                / <a href="/service/hospitals/regions/13003269#174">участок 1</a>											 / <a href="/service/record/908205/36852/timetable">Бодрова Разия Фазлыевна</a>
            </p>
            <p><a class="isAttachmentWrong" href="#">Сообщить о неверном прикреплении</a></p>
        </div>
        <div class="clearFix"></div>
    </div>        <ul class="steps step1">
        <li><a href="/service/record/908205/profiles">Выберите специальность</a></li>
        <li><span>Специалист</span></li>
        <li><span>Дата и время</span></li>
    </ul>


    <h1>Поиск врача</h1>
    <form class="doc_search">
        <p class="inputFieldwithCase">
            <input value="908205" id="Person_id" type="hidden">
            <input autocomplete="off" class="autoCompleteInput ui-autocomplete-input" placeholder="Введите ФИО или специальность врача" type="text">
            <a class="button search"></a>
        </p>
    </form>

    <dl class="selectDoc filtered">
        <dt class="allDoctors selected" style="display: none;"></dt>
        <dd>
            <ul>
                <li>
                    <ul>
                        <span class="big">А</span>
                        <?php foreach ($professions as $profession){ ?>
                            <li><?=\yii\bootstrap\Html::a($profession->prof_name, ['service/record', 'id'=>$profession->id, 'title'=>"doctors", 'step'=>2])?></li>
                        <? } ?>
                        <li><a href="/service/record/908205/402182/0/doctors">Акушер - гинеколог</a></li>
                        <li><a href="/service/record/908205/35124/0/doctors">Аллерголог-иммунолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">В</span>
                        <li><a href="/service/record/908205/0/203/doctors">Врач общей практики-семейный врач</a></li>
                        <li><a href="/service/record/908205/35231/0/doctors">Врач функциональной диагностики</a></li>
                    </ul></li>
                <li>
                    <ul>
                        <span class="big">Г</span>
                        <li><a href="/service/record/908205/35131/0/doctors">Гастроэнтеролог</a></li>
                        <li><a href="/service/record/908205/35132/0/doctors">Гематолог</a></li>
                    </ul
                </li>
                <li>
                    <ul>
                        <span class="big">Д</span>
                        <li>
                            <a href="/service/record/908205/35136/0/doctors">Дерматовенеролог</a>
                        </li>
                        <li>
                            <a href="/service/record/908205/35206/0/doctors">Детский стоматолог</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">И</span>
                        <li>
                            <a href="/service/record/908205/35148/0/doctors">Инфекционист</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">К</span>
                        <li>
                            <a href="/service/record/908205/35149/0/doctors">Кардиолог</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Л</span>
                        <li><a href="/service/record/908205/35154/0/doctors">Лабораторной диагностики</a></li>
                        <li><a href="/service/record/908205/35161/0/doctors">Лечебная физкультура</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Н</span>
                        <li><a href="/service/record/908205/35173/0/doctors">Невролог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">О</span>
                        <li><a href="/service/record/908205/35180/0/doctors">Онколог</a></li>
                        <li><a href="/service/record/908205/35184/0/doctors">Оториноларинголог</a></li>
                        <li><a href="/service/record/908205/35185/0/doctors">Офтальмолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">П</span>
                        <li><a href="/service/record/908205/35188/0/doctors">Педиатр</a></li>
                        <li><a href="/service/record/908205/35195/0/doctors">Пульмонолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Р</span>
                        <li><a href="/service/record/908205/35197/0/doctors">Ревматолог</a></li>
                        <li><a href="/service/record/908205/35198/0/doctors">Рентгенолог</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">С</span>
                        <li><a href="/service/record/908205/35205/0/doctors">Стоматолог</a></li>
                        <li><a href="/service/record/908205/35210/0/doctors">Стоматолог хирург</a></li>
                        <li><a href="/service/record/908205/35208/0/doctors">Стоматолог-ортопед</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Т</span>
                        <li><a href="/service/record/908205/35217/0/doctors">Терапевт и врач общ. практики</a></li>
                        <li><a href="/service/record/908205/35220/0/doctors">Травматолог-ортопед</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">У</span>
                        <li><a href="/service/record/908205/35226/0/doctors">Ультразвуковой диагностики</a></li>
                        <li><a href="/service/record/908205/35228/0/doctors">Уролог</a></li>
                        <li><a href="/service/record/908205/35139/0/doctors">Уролог детский</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Ф</span>
                        <li><a href="/service/record/908205/35229/0/doctors">Физиотерапевт</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Х</span>
                        <li><a href="/service/record/908205/35232/0/doctors">Хирург</a></li>
                        <li><a href="/service/record/908205/35140/0/doctors">Хирург детский</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Ц</span>
                        <li><a href="/service/record/908205/35255/0/doctors">Центр здоровья</a></li>
                    </ul>
                </li>
                <li>
                    <ul>
                        <span class="big">Э</span>
                        <li><a href="/service/record/908205/35242/0/doctors">Эндокринолог</a></li>
                        <li><a href="/service/record/908205/35141/0/doctors">Эндокринолог детский</a></li>
                        <li><a href="/service/record/908205/35243/0/doctors">Эндоскопист</a></li>
                    </ul>
                </li>
            </ul>
        </dd>
    </dl>
</div>

modules/service/views/record/record_table.php
<?php
/* @var $this yii\web\View */
?>
<div class="wrapper">
    <div class="docRecordingBlock">
        <h1><a href="/user/cards"><?=\Yii::$app->user->identity->name?> <?=\Yii::$app->user->identity->family?></a> <span>записывается к врачу</span></h1>
        <div class="clientLpuAttachmentsTab"><span>Прикрепление</span></div>
        <div class="clientLpuAttachments">
            <p><span>
				Основное прикрепление:
				</span>
                <a href="/service/hospitals/view/13003269">ГБУЗ АО "ГП №2", г Астрахань, ул Соликамская, д 8</a>
                / <a href="/service/hospitals/regions/13003269#174">участок 1</a> / <a href="/service/record/908205/36852/timetable">Бодрова Разия Фазлыевна</a>
            </p>
            <p><a class="isAttachmentWrong" href="#">Сообщить о неверном прикреплении</a></p>
        </div>
        <div class="clearFix"></div>
    </div>
    <ul class="steps step2">
        <li><a href="/service/record/profiles"><?=$professionName?></a></li>
        <li><a href="/service/record/908205/35205/1/doctors">Выберите врача</a></li>
        <li><span>Дата и время</span></li>
    </ul>
    <h1>Поликлиника прикрепления (ГБУЗ АО "ГП №2")</h1>
    <div class="sortByBlock">
        Упорядочить:
        <span class="selToggler">
            <a class="selectedToggler" href="#" id="sortMyDoctorsByName">по фамилии</a>
            <a href="#" id="sortMyDoctorsByRecord">по ближайшей записи</a>
        </span>
    </div>
    <div class="docsInLpuTable">
        <div class="headerDocsInLpuTable">
            <span class="headerDocsInLpuTableSpec">Специалист</span>
            <span class="headerDocsInLpuTableNearestRec">Ближайшая запись</span>
            <span class="headerDocsInLpuTableSpecMark">Оценка</span>
            <span class="headerDocsInLpuTableSpecFeeds">Отзывы</span>
        </div>
        <div class="docsInLpuTableDetail">
            <?php
            $lastWork = "";
            foreach($doctors as $doctor){ ?>
                <div class="Lpuunit" id="lpuunit_26">
            <?php
                if($lastWork != $doctor->work){ ?>
                    <div class="docsInLpuTableDescr">
                        <a class="lpu-fullName" href="<?=\Yii::$app->urlManager->createUrl(['service/hospitals/view', 'id'=>$doctor->getWork()->one()->id])?>"> <?=$doctor->getWork()->one()->name?></a>
                        <span class="lpu-address"><?=$doctor->getWork()->one()->getRegion()->one()->name?>, <?=$doctor->getWork()->one()->address?></span>
                    </div>
                <? }
                $lastWork = $doctor->work;
                ?>
                    <a href="<?=\Yii::$app->urlManager->createUrl(['service/schedule/timetable', 'id'=>$doctor->id, 'step'=>3])?>">
                                    <span class="doc-photo">
                                        <img src="/img/logo.png">
                                    </span>
                        <span class="doc-name"><?=$doctor->full_name?></span>
                        <span class="Freetime hidden">empty</span>
                        <span class="nearest-record"></span>
                        <div class="mark-stars stars0"></div>
                        <span class="count-feedbacks">0</span>
                    </a>
                </div>

            <? } ?>
        </div>
    </div>
    <div class="docsInLpuTablePostInfoBlock">
        <a href="#" class="button grey" id="otherDoctors">Найти специалиста в другой поликлинике</a>
    </div>
</div>

modules/service/views/record/regions.php
<?php
/* @var $this yii\web\View */
?>
<h1>service/regions</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

modules/service/views/record/search.php
<?php
/* @var $this yii\web\View */
?>
<div class="wrapper">
    <div class="docsInLpuTable">
        <div class="headerDocsInLpuTable">
            <span class="headerDocsInLpuTableSpec">Специалист</span>
            <span class="headerDocsInLpuTableNearestRec">Ближайшая запись</span>
            <span class="headerDocsInLpuTableSpecMark">Оценка</span>
            <span class="headerDocsInLpuTableSpecFeeds">Отзывы</span>
        </div>
        <div class="docsInLpuTableDetail">
            <?php
            $lastWork = "";
            foreach($result as $doctor){ ?>
                <div class="Lpuunit" id="lpuunit_26">
                    <a href="<?=\Yii::$app->urlManager->createUrl(['service/schedule/timetable', 'id'=>$doctor->id, 'step'=>3])?>">
                                    <span class="doc-photo">
                                        <img src="/img/logo.png">
                                    </span>
                        <span class="doc-name"><?=$doctor->full_name?></span>
                        <span class="Freetime hidden">empty</span>
                        <span class="nearest-record"></span>
                        <div class="mark-stars stars0"></div>
                        <span class="count-feedbacks">0</span>
                    </a>
                </div>

            <?php } ?>
        </div>
    </div>
</div>

modules/service/views/schedule/info.php
<div class="wrapper">
    <div class="activeWrDocHead">
        <div class="activeWrDocContainer">
            <span class="docname"><?=$doctor->full_name?></span>
            <span class="docspec"><?=$doctor->getProfession()->one()->prof_name?></span>
        </div>
        <div class="addictiveRightLinks">
				<span class="selToggler">
					<a href="<?=\Yii::$app->urlManager->createUrl(['service/schedule/timetable', 'id'=>$doctor->id])?>">Ish jadvali</a>
					<a href="<?=\Yii::$app->urlManager->createUrl(['service/schedule/info', 'id'=>$doctor->id])?>" class="selectedToggler">Doktor ma'lumotlari</a>
                </span>
        </div>
    </div>
    <div class="docCardBlock">
        <div class="docPhoto">
            <img style="width:160px;" src="/<?=$doctor->picture?>">
        </div>
        <div class="docInfoBlock">
            <?=$doctor->about?>
        </div>
        <div class="clearFix"></div>
    </div>
</div>